version: '3.6'

services:
  nginx:
    image: nginx:alpine
    container_name: web-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static:/var/www
    networks:
      - spider-network

  spider-service:
    build: ./rank-spider
    container_name: spider-service
    volumes:
      - result-data:/app/data
    networks:
      - spider-network
    environment:
      - TZ=Asia/Ho_Chi_Minh

networks:
  spider-network:
    driver: bridge

volumes:
  result-data:
